<?php
/**
 * Hook install
 */

function core_enhancements_install() {
  
  //set variables
  variable_set( 'core_enhancements_views_strip_keys_keys', 'node_;data_;_value;field_;__');
  variable_set( 'core_enhancements_enable_jquery_carousel' , 0 );
  variable_set( 'core_enhancements_enable_jquery_cycle' , 0 );
  variable_set( 'core_enhancements_enable_jquery_maskedinput' , 0 );
  variable_set( 'core_enhancements_enable_jquery_orbitaltooltip' , 0 );
  
}

/**
 * Hook uninstall
 */
function core_enhancements_uninstall() {
  
  //set variables
  variable_del( 'core_enhancements_views_strip_keys_keys');
  variable_del( 'core_enhancements_enable_jquery_carousel');
  variable_del( 'core_enhancements_enable_jquery_cycle');
  variable_del( 'core_enhancements_enable_jquery_maskedinput');
  variable_del( 'core_enhancements_enable_jquery_orbitaltooltip');
  
}

/**
 * TODO: Add some information after install, to point them to the enhancements page,
 * and the current release information, make sure to add BETA warnings
 */